### PR TITLE
Make tags translatable

### PR DESCRIPTION
**Pull request by marcelklehr**
Allow the transifex bot to pick up tags for translation

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by linuzer** [comment]
May I ask, how this change is intended to work? So how can I actually create a translation?
I wasn't able to find any information on this.

**Comment by marcelklehr** [comment]
@linuzer Translations are handled via transifex as for most Nextcloud projects: https://explore.transifex.com/nextcloud/nextcloud/ :)

**Comment by linuzer** [comment]
@marcelklehr Thanks for the quick response! 
But sorry, I guess I'm not getting the point... Are you telling me, I have to sign up to transifex to create a translation for my tags? In other words are these tags considered an internal part of Nextcloud just like the elements of the UI and as long as no one creates a translation in a particular language, they only exist in English?

**Comment by marcelklehr** [comment]
> as long as no one creates a translation in a particular language, they only exist in English?

yes. You can still rename tags, but tags created by recognize will be tried to auomatically translated to the language you have set.

**Comment by marcelklehr** [comment]
It seems that loading these translations in the photos app is currently broken, though, this will be fixed in 25.0.1

**Comment by linuzer** [comment]
Ah, thanks for the explanation! Now it makes sense... ;-)

**Pull request merged**
