### PR TITLE
Adding "Info" as a message type

### LINKED ISSUE #1059: Differentiate between info/notices and warnings in admin panel
### Describe the feature you'd like to request

The job status windows in the admin settings are misleading when presented with the 'warning' exclamation and orange background.

Example: these are not errors, but look like a problem:
image

### Describe the solution you'd like

Show non-error status information with blue background and (i) image.
image

### Describe alternatives you've considered

none

### PR DESCRIPTION
**Pull request by Olen**
Also added explicit "type=warning" to the relevant cards to add readability.

Should fix #1059

### CODE REVIEW

**Comment by marcelklehr** [comment]
Thank you for opening this!
As is, I think this will not work however, as recognize is still using nextcloud-vue v7 which doesn't have the info type yet. So, we need to upgrade to nextcloud-vue v8, which I've been putting off because god knows what will break with that upgrade... :S

**Comment by Olen** [comment]
Ah, ok. 
This is my first PR for Nextcloud, so I am not familiar with all the dependencies.  But it is at least a start, I hope.
Someone with a better dev-environment than me should probably test the upgrade to v8.  It will probably be required at some point anyway...

**Comment by Olen** [comment]
Uhm. 
That commit did not actually close this, did it?
But it was a requirement for this PR to be merged?

**Comment by marcelklehr** [comment]
I merged your commit via cli: d2856ad9038621e510740ea6dd1b364bc88348b5

**Comment by Olen** [comment]
Thank you.
Glad to see some development here.  Recognize is great, but still needs a little love.

**Comment by marcelklehr** [comment]
Yeah, I completely agree. :)

**Pull request closed without merging**
