### PR TITLE
Add option to only retry non-tagged files in classify

### PR DESCRIPTION
**Pull request by nielstron**
This is picking up https://github.com/nextcloud/recognize/issues/1137 again.

Works locally, no idea how to unit test this :)

### CODE REVIEW

**Comment by marcelklehr** [comment]
Hey @nielstron 

Really cool that you're taking this on! I'll look into this soon

**Comment by marcelklehr** [comment]
This approach works in so far as it does indeed restrict the classify command to files that haven't been tagged with the recognize tag yet. However: The recognize tag is only assigned by the imagenet, movinet and musicnn classifiers, not by the face recognition classifier. So, when e.g. the classify command fails or is stopped during the imagenet classification, the images it has tagged so far will not be put through face recognition at all, because they have the tag from the imagenet classification run.

**Review by marcelklehr — CHANGES_REQUESTED** [review]
This approach works in so far as it does indeed restrict the classify command to files that haven't been tagged with the recognize tag yet. However: The recognize tag is only assigned by the imagenet, movinet and musicnn classifiers, not by the face recognition classifier. So, when e.g. the classify command fails or is stopped during the imagenet classification, the images it has tagged so far will not be put through face recognition at all, because they have the tag from the imagenet classification run.

**Comment by nielstron** [comment]
I see two options
1) Determine seperate whether the face classification pipeline has been run for a file and put it into the queue if not
2) always put the file in the face classification queue (which I fear to be quite expensive)

For 1 it would be good to know if such a tag exists/how to obtain it.

**Comment by marcelklehr** [comment]
Yeah, I agree with your assessment, for 1. you can find if a face detection exists for a file using the following method: https://github.com/nextcloud/recognize/blob/main/lib/Db/FaceDetectionMapper.php#L82

**Comment by nielstron** [comment]
If face detection for a file did not find a face, is the fact that we processed the file still stored somewhere? Or would this re-run classification on all files that don't contain a face?

**Comment by marcelklehr** [comment]
Ah, good question. There's no marker for whether a file has been through face recognition. It might make sense to introduce a new magic tag for this.

**Comment by nielstron** [comment]
Okay. This patch now skips running the no-face-recognition classification for tagged files. I don't think I will have time to contribute more elaborate features in the near future.

**Review by marcelklehr — APPROVED** [review]
Cool, this works well enough! Thank you!

**Comment by marcelklehr** [comment]
Hi @nielstron 
Thank you again for your work on this @ghisch 💙 We appreciate your effort and the work you've put into this PR.
I'd like to invite you to our [Developer Community Chat](https://cloud.nextcloud.com/call/xs25tz5y). Hit me up if you would like a guest account for that instance!

Cheers
Marcel

**Pull request merged**
