### PR TITLE
Use nextcloud preview provider for generating tempfiles

### PR DESCRIPTION
**Pull request by marcelklehr**
Should fix OOM errors by 

 - using the OCP preview provider which has wider availability than simply relying on imagick being installed
 - not classifying files over 8MB

fixes https://github.com/nextcloud/recognize/issues/474
fixes https://github.com/nextcloud/recognize/issues/370

### CODE REVIEW

**Comment by marcelklehr** [comment]
Not sure why psalm thinks I'm not setting the property :S Any insights anyone?

**Review by pulsejet — APPROVED** [review]
LGTM. This is what I originally intended to do anyway.

**Comment by juliushaertl** [comment]
It seemed that psalm basically failed to further analyse the constructor because of the muted error of the private class dependency of `\OC\Hooks\Emitter` on `IRootFolder`. The same error was already there for the other properties, but that should work now. Having the stub might be a good idea in general :)

**Comment by marcelklehr** [comment]
> on larger instances you might want to keep the amount of regenerated previews rather to the minimum for storage reasons

We can adjust the requested size to be the default preview size, so that nothing needs to be regenerated, what would that be?

**Comment by marcelklehr** [comment]
1024 seems to be part of the default of previewgenerator app

**Comment by htc1977** [comment]
Can I pull the git into an installed app folder within my custom_apps folder without any issues or should I wait for an "official" app update?

**Comment by marcelklehr** [comment]
I recommend waiting for an official update. I'll publish it later today.

**Pull request merged**
