### PR TITLE
feat(dav): Add an unassigned-faces DAV collection

### LINKED ISSUE #442: Faces with cluster_id NULL
What's going to happen with faces that have been removed from clusters, can we maybe get a "Unknown Person" cluster element in Photos/Memories that has all the removed and not yet assigned faces in it?  (so basically all with cluster_id = NULL)

Currently if you delete a face from a cluster (remove from person) it won't show up anywhere in the UI any more, right?

### PR DESCRIPTION
**Pull request by marcelklehr**
fixes #442

also see https://github.com/nextcloud/photos/pull/1832

### CODE REVIEW

**Comment by marcelklehr** [comment]
cc @pulsejet in case you want to implement this :)

**Comment by pulsejet** [comment]
@marcelklehr I just noticed `findRejectedByUserId` checks for `cluster_id=-1`, but the photos that never got clustered seem to have `cluster_id=NULL` for me. Did this/something change at some point?

**Comment by marcelklehr** [comment]
> Did this/something change at some point?

Yes. -1 is a new category for "ran through clustering but didn't find a match". NULL on the other hand means, "not run through clustering yet". These used to be NULL in both cases, but that leads to a high number of "rejects" being reintroduced into the clustering every run. Now we only let in a few of the rejects each run to avoid "poisoning the well".

**Comment by pulsejet** [comment]
Ah nice, thanks. So I'm assuming the cron job would fix the `NULL` to `-1` eventually.

**Pull request merged**
